import type { SkillSeed } from "../../core/types";

export const PERFORMANCE_ONLY_LEVEL = 999;

export const VARIANT_CATEGORY_BY_PARENT: Record<string, string> = {
  flexoes: "peito",
  agachamentos: "pernas",
  pranchas: "core",
  abdominais: "core",
};

export const coreSkillSeeds: SkillSeed[] = [
  {
    name: "Flexão",
    category: "peito",
    difficulty: "basico",
    tier: "iniciante",
    requiredLevel: 1,
    description: "Empurrar horizontal com peso corporal",
    unlockMessage: "Flexão desbloqueada.",
  },
  {
    name: "Agachamento",
    category: "pernas",
    difficulty: "basico",
    tier: "iniciante",
    requiredLevel: 1,
    description: "Base para força de membros inferiores",
    unlockMessage: "Agachamento desbloqueado.",
  },
  {
    name: "Abdominal",
    category: "core",
    difficulty: "basico",
    tier: "iniciante",
    requiredLevel: 1,
    description: "Fortalecimento de core",
    unlockMessage: "Abdominal desbloqueado.",
  },
  {
    name: "Prancha",
    category: "core",
    difficulty: "basico",
    tier: "iniciante",
    requiredLevel: 1,
    description: "Isometria de core",
    unlockMessage: "Prancha desbloqueada.",
  },
  {
    name: "Caminhada leve",
    category: "cardio",
    difficulty: "basico",
    tier: "iniciante",
    requiredLevel: 1,
    description: "Volume de passos e cardio leve (base para condicionamento)",
    unlockMessage: "Caminhada leve desbloqueada.",
  },
  {
    name: "Barra Fixa",
    category: "costas",
    difficulty: "intermediario",
    tier: "intermediario",
    requiredLevel: 5,
    description: "Puxada vertical",
    unlockMessage: "Barra fixa disponível.",
  },
  {
    name: "Dips",
    category: "triceps",
    difficulty: "intermediario",
    tier: "intermediario",
    requiredLevel: 7,
    description: "Empurrar em barras paralelas",
    unlockMessage: "Dips desbloqueado.",
  },
  {
    name: "Handstand",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 6,
    description: "Progressão de equilíbrio invertido",
    unlockMessage: "Inicie sua jornada no handstand.",
    prerequisites: ["Prancha"],
    attributeRequirements: { strength: 20, dexterity: 20 },
  },
  {
    name: "Front Lever",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 10,
    description: "Alavanca frontal",
    unlockMessage: "Front Lever desbloqueado.",
    prerequisites: ["Barra Fixa"],
    attributeRequirements: { strength: 30 },
  },
  {
    name: "Back Lever",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 10,
    description: "Alavanca posterior",
    unlockMessage: "Back Lever desbloqueado.",
    prerequisites: ["Barra Fixa"],
    attributeRequirements: { strength: 30 },
  },
  {
    name: "Planche",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 12,
    description: "Sustentação horizontal",
    unlockMessage: "Planche desbloqueada.",
    prerequisites: ["Dips"],
    attributeRequirements: { strength: 38 },
  },
  {
    name: "Human Flag",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 14,
    description: "Bandeira humana",
    unlockMessage: "Human Flag desbloqueada.",
    attributeRequirements: { strength: 42, dexterity: 30 },
  },
  {
    name: "Muscle Up",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 11,
    description: "Transição de barra",
    unlockMessage: "Muscle Up desbloqueado.",
    prerequisites: ["Barra Fixa", "Dips"],
    attributeRequirements: { strength: 36 },
  },
  {
    name: "Pistol Squat",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 9,
    description: "Agachamento unilateral",
    unlockMessage: "Pistol Squat desbloqueado.",
    prerequisites: ["Agachamento"],
    attributeRequirements: { vitality: 28 },
  },
  {
    name: "Dragon Flag",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 13,
    description: "Core avançado",
    unlockMessage: "Dragon Flag desbloqueada.",
    prerequisites: ["Abdominal"],
    attributeRequirements: { strength: 34, focus: 24 },
  },
  {
    name: "L-Sit",
    category: "calistenia",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 8,
    description: "Sustentação em L",
    unlockMessage: "L-Sit desbloqueado.",
    prerequisites: ["Prancha"],
    attributeRequirements: { strength: 24, focus: 18 },
  },
  {
    name: "Crow Pose",
    category: "yoga",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 6,
    description: "Equilíbrio em braços",
    unlockMessage: "Crow Pose desbloqueada.",
    attributeRequirements: { focus: 18, dexterity: 18 },
  },
  {
    name: "Headstand",
    category: "yoga",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 8,
    description: "Invertida na cabeça",
    unlockMessage: "Headstand desbloqueada.",
    attributeRequirements: { strength: 22, focus: 22 },
  },
  {
    name: "Wheel Pose",
    category: "yoga",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 9,
    description: "Ponte avançada",
    unlockMessage: "Wheel Pose desbloqueada.",
    attributeRequirements: { vitality: 20 },
  },
  {
    name: "Firefly Pose",
    category: "yoga",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 11,
    description: "Equilíbrio avançado",
    unlockMessage: "Firefly Pose desbloqueada.",
    attributeRequirements: { strength: 28, focus: 22 },
  },
  {
    name: "Eight Angle Pose",
    category: "yoga",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 12,
    description: "Torção com braços",
    unlockMessage: "Eight Angle Pose desbloqueada.",
    attributeRequirements: { dexterity: 30, focus: 24 },
  },
  {
    name: "Scorpion Pose",
    category: "yoga",
    difficulty: "calistenia",
    tier: "calistenico",
    requiredLevel: 15,
    description: "Invertida avançada",
    unlockMessage: "Scorpion Pose desbloqueada.",
    attributeRequirements: { strength: 35, dexterity: 32 },
  },
];
