begin;

create table if not exists social.user_presence (
  user_id text primary key references core.users(id) on delete cascade,
  presence_status text not null default 'offline',
  visibility text not null default 'friends',
  source text not null default 'app',
  session_id text,
  current_activity text,
  metadata_json jsonb not null default '{}'::jsonb,
  last_heartbeat_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint user_presence_status_check check (presence_status in ('online', 'away', 'offline')),
  constraint user_presence_visibility_check check (visibility in ('friends', 'private', 'public'))
);

create table if not exists social.friend_activity_events (
  id bigint generated by default as identity primary key,
  actor_user_id text not null references core.users(id) on delete cascade,
  target_user_id text references core.users(id) on delete set null,
  activity_type text not null,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_user_presence_status_heartbeat
  on social.user_presence (presence_status, last_heartbeat_at desc);
create index if not exists idx_user_presence_last_seen
  on social.user_presence (last_seen_at desc);
create index if not exists idx_user_presence_visibility
  on social.user_presence (visibility);

create index if not exists idx_friend_activity_actor_created
  on social.friend_activity_events (actor_user_id, created_at desc);
create index if not exists idx_friend_activity_target_created
  on social.friend_activity_events (target_user_id, created_at desc);
create index if not exists idx_friend_activity_type_created
  on social.friend_activity_events (activity_type, created_at desc);

create or replace trigger trg_user_presence_touch_updated_at
before update on social.user_presence
for each row execute function core.touch_updated_at();

alter table social.user_presence enable row level security;
alter table social.friend_activity_events enable row level security;

drop policy if exists service_role_full on social.user_presence;
create policy service_role_full
on social.user_presence
for all
to service_role
using (true)
with check (true);

drop policy if exists service_role_full on social.friend_activity_events;
create policy service_role_full
on social.friend_activity_events
for all
to service_role
using (true)
with check (true);

drop policy if exists authenticated_presence_select on social.user_presence;
create policy authenticated_presence_select
on social.user_presence
for select
to authenticated
using (
  user_id = (select core.request_user_id())
  or visibility = 'public'
  or (
    visibility = 'friends'
    and exists (
      select 1
      from social.friendships f
      where f.user_id = (select core.request_user_id())
        and coalesce(f.friend_id, f.friend_user_id) = social.user_presence.user_id
        and f.status = 'accepted'
    )
  )
);

drop policy if exists authenticated_presence_insert_self on social.user_presence;
create policy authenticated_presence_insert_self
on social.user_presence
for insert
to authenticated
with check (user_id = (select core.request_user_id()));

drop policy if exists authenticated_presence_update_self on social.user_presence;
create policy authenticated_presence_update_self
on social.user_presence
for update
to authenticated
using (user_id = (select core.request_user_id()))
with check (user_id = (select core.request_user_id()));

drop policy if exists authenticated_presence_delete_self on social.user_presence;
create policy authenticated_presence_delete_self
on social.user_presence
for delete
to authenticated
using (user_id = (select core.request_user_id()));

drop policy if exists authenticated_friend_activity_select on social.friend_activity_events;
create policy authenticated_friend_activity_select
on social.friend_activity_events
for select
to authenticated
using (
  actor_user_id = (select core.request_user_id())
  or target_user_id = (select core.request_user_id())
  or exists (
    select 1
    from social.friendships f
    where f.user_id = (select core.request_user_id())
      and coalesce(f.friend_id, f.friend_user_id) = social.friend_activity_events.actor_user_id
      and f.status = 'accepted'
  )
);

drop policy if exists authenticated_friend_activity_insert_actor on social.friend_activity_events;
create policy authenticated_friend_activity_insert_actor
on social.friend_activity_events
for insert
to authenticated
with check (actor_user_id = (select core.request_user_id()));

drop policy if exists authenticated_friend_activity_update_actor on social.friend_activity_events;
create policy authenticated_friend_activity_update_actor
on social.friend_activity_events
for update
to authenticated
using (actor_user_id = (select core.request_user_id()))
with check (actor_user_id = (select core.request_user_id()));

drop policy if exists authenticated_friend_activity_delete_actor on social.friend_activity_events;
create policy authenticated_friend_activity_delete_actor
on social.friend_activity_events
for delete
to authenticated
using (actor_user_id = (select core.request_user_id()));

create or replace view social.friend_online_presence as
select
  f.user_id,
  up.user_id as friend_user_id,
  up.presence_status,
  up.visibility,
  up.last_heartbeat_at,
  up.last_seen_at,
  (
    up.presence_status = 'online'
    and up.last_heartbeat_at >= timezone('utc', now()) - interval '5 minutes'
  ) as is_online
from social.friendships f
inner join social.user_presence up
  on up.user_id = coalesce(f.friend_id, f.friend_user_id)
where f.status = 'accepted';

create or replace view compat.user_presence as
select * from social.user_presence;

create or replace view compat.friend_activity_events as
select * from social.friend_activity_events;

grant all on social.user_presence to service_role;
grant all on social.friend_activity_events to service_role;
grant all on all sequences in schema social to service_role;

commit;
