begin;

alter table if exists catalog.achievements
  add column if not exists xp_reward integer not null default 50;

alter table if exists catalog.achievements
  add column if not exists points_reward integer not null default 0;

alter table if exists catalog.titles
  add column if not exists xp_reward integer not null default 0;

alter table if exists catalog.titles
  add column if not exists points_reward integer not null default 0;

create table if not exists gameplay.user_reward_notifications (
  id bigint generated by default as identity primary key,
  user_id text not null references core.users(id) on delete cascade,
  type text not null,
  entity_name text,
  level integer,
  xp_reward integer not null default 0,
  points_reward integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  consumed_at timestamptz
);

create index if not exists idx_user_reward_notifications_user_pending
  on gameplay.user_reward_notifications (user_id, consumed_at, id);

alter table gameplay.user_reward_notifications enable row level security;

drop policy if exists service_role_full on gameplay.user_reward_notifications;
create policy service_role_full
on gameplay.user_reward_notifications
for all
to service_role
using (true)
with check (true);

drop policy if exists authenticated_self on gameplay.user_reward_notifications;
create policy authenticated_self
on gameplay.user_reward_notifications
for all
to authenticated
using (user_id = (select core.request_user_id()))
with check (user_id = (select core.request_user_id()));

create or replace view compat.achievements as
select
  id,
  name,
  description,
  rarity,
  icon,
  requirement_type,
  requirement_value,
  created_at,
  updated_at,
  category,
  color,
  secret,
  condition,
  reference,
  xp_reward,
  points_reward
from catalog.achievements;

create or replace view compat.titles as
select
  id,
  name,
  rarity,
  requirement_type,
  requirement_value,
  created_at,
  updated_at,
  description,
  reference,
  unlock_condition,
  xp_reward,
  points_reward
from catalog.titles;

create or replace view compat.user_reward_notifications as
select * from gameplay.user_reward_notifications;

grant all on gameplay.user_reward_notifications to service_role;
grant all on all sequences in schema gameplay to service_role;

commit;
