begin;

create table if not exists telemetry.offline_sync_operations (
  id bigint generated by default as identity primary key,
  user_id text not null references core.users(id) on delete cascade,
  operation_id text not null,
  operation_type text not null,
  occurred_at timestamptz not null,
  source text not null,
  confidence text,
  request_payload jsonb,
  response_payload jsonb,
  status text not null default 'processed',
  processed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_offline_sync_operations_user_operation
  on telemetry.offline_sync_operations (user_id, operation_id);

create index if not exists idx_offline_sync_operations_user_processed
  on telemetry.offline_sync_operations (user_id, processed_at desc);

alter table telemetry.offline_sync_operations enable row level security;

drop policy if exists service_role_full on telemetry.offline_sync_operations;
create policy service_role_full
on telemetry.offline_sync_operations
for all
to service_role
using (true)
with check (true);

drop policy if exists authenticated_self on telemetry.offline_sync_operations;
create policy authenticated_self
on telemetry.offline_sync_operations
for all
to authenticated
using (user_id = (select core.request_user_id()))
with check (user_id = (select core.request_user_id()));

create or replace view compat.offline_sync_operations as
select * from telemetry.offline_sync_operations;

grant all on telemetry.offline_sync_operations to service_role;
grant all on all sequences in schema telemetry to service_role;

commit;
