begin;

create table if not exists social.conversations (
  id bigint generated by default as identity primary key,
  conversation_kind text not null default 'direct',
  direct_key text unique,
  title text,
  created_by_user_id text references core.users(id) on delete set null,
  last_message_id bigint,
  last_message_preview text,
  last_message_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint conversations_kind_check check (conversation_kind in ('direct', 'group'))
);

create table if not exists social.conversation_members (
  conversation_id bigint not null references social.conversations(id) on delete cascade,
  user_id text not null references core.users(id) on delete cascade,
  member_role text not null default 'member',
  joined_at timestamptz not null default timezone('utc', now()),
  last_read_message_id bigint,
  last_read_at timestamptz,
  last_notified_message_id bigint,
  last_notified_at timestamptz,
  notifications_muted boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (conversation_id, user_id),
  constraint conversation_members_role_check check (member_role in ('owner', 'member'))
);

create table if not exists social.conversation_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references social.conversations(id) on delete cascade,
  sender_user_id text not null references core.users(id) on delete cascade,
  message_text text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  edited_at timestamptz,
  deleted_at timestamptz,
  constraint conversation_messages_text_length_check
    check (char_length(trim(message_text)) between 1 and 2000)
);

create index if not exists idx_conversations_kind_last_message
  on social.conversations (conversation_kind, last_message_at desc, id desc);
create index if not exists idx_conversations_direct_key
  on social.conversations (direct_key);
create index if not exists idx_conversation_members_user
  on social.conversation_members (user_id, updated_at desc);
create index if not exists idx_conversation_messages_thread
  on social.conversation_messages (conversation_id, id desc);
create index if not exists idx_conversation_messages_sender
  on social.conversation_messages (sender_user_id, created_at desc);

create or replace trigger trg_conversations_touch_updated_at
before update on social.conversations
for each row execute function core.touch_updated_at();

create or replace trigger trg_conversation_members_touch_updated_at
before update on social.conversation_members
for each row execute function core.touch_updated_at();

create or replace trigger trg_conversation_messages_touch_updated_at
before update on social.conversation_messages
for each row execute function core.touch_updated_at();

alter table social.conversations enable row level security;
alter table social.conversation_members enable row level security;
alter table social.conversation_messages enable row level security;

drop policy if exists service_role_full on social.conversations;
create policy service_role_full
on social.conversations
for all
to service_role
using (true)
with check (true);

drop policy if exists service_role_full on social.conversation_members;
create policy service_role_full
on social.conversation_members
for all
to service_role
using (true)
with check (true);

drop policy if exists service_role_full on social.conversation_messages;
create policy service_role_full
on social.conversation_messages
for all
to service_role
using (true)
with check (true);

drop policy if exists authenticated_conversations_select on social.conversations;
create policy authenticated_conversations_select
on social.conversations
for select
to authenticated
using (
  exists (
    select 1
    from social.conversation_members cm
    where cm.conversation_id = social.conversations.id
      and cm.user_id = (select core.request_user_id())
  )
);

drop policy if exists authenticated_conversations_insert_self on social.conversations;
create policy authenticated_conversations_insert_self
on social.conversations
for insert
to authenticated
with check (created_by_user_id = (select core.request_user_id()));

drop policy if exists authenticated_conversation_members_select on social.conversation_members;
create policy authenticated_conversation_members_select
on social.conversation_members
for select
to authenticated
using (
  user_id = (select core.request_user_id())
  or exists (
    select 1
    from social.conversation_members cm
    where cm.conversation_id = social.conversation_members.conversation_id
      and cm.user_id = (select core.request_user_id())
  )
);

drop policy if exists authenticated_conversation_messages_select on social.conversation_messages;
create policy authenticated_conversation_messages_select
on social.conversation_messages
for select
to authenticated
using (
  exists (
    select 1
    from social.conversation_members cm
    where cm.conversation_id = social.conversation_messages.conversation_id
      and cm.user_id = (select core.request_user_id())
  )
);

drop policy if exists authenticated_conversation_messages_insert on social.conversation_messages;
create policy authenticated_conversation_messages_insert
on social.conversation_messages
for insert
to authenticated
with check (
  sender_user_id = (select core.request_user_id())
  and exists (
    select 1
    from social.conversation_members cm
    where cm.conversation_id = social.conversation_messages.conversation_id
      and cm.user_id = (select core.request_user_id())
  )
);

create or replace view compat.conversations as
select * from social.conversations;

create or replace view compat.conversation_members as
select * from social.conversation_members;

create or replace view compat.conversation_messages as
select * from social.conversation_messages;

grant all on social.conversations to service_role;
grant all on social.conversation_members to service_role;
grant all on social.conversation_messages to service_role;
grant all on all sequences in schema social to service_role;

commit;
