begin;

create table if not exists social.user_blocks (
  blocker_user_id text not null references core.users(id) on delete cascade,
  blocked_user_id text not null references core.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (blocker_user_id, blocked_user_id),
  constraint user_blocks_distinct_check check (blocker_user_id <> blocked_user_id)
);

create index if not exists idx_user_blocks_blocked
  on social.user_blocks (blocked_user_id, created_at desc);

alter table social.conversation_messages
  add column if not exists message_kind text not null default 'text';

alter table social.conversation_messages
  alter column message_text drop not null;

alter table social.conversation_messages
  drop constraint if exists conversation_messages_kind_check;

alter table social.conversation_messages
  drop constraint if exists conversation_messages_text_length_check;

alter table social.conversation_messages
  add constraint conversation_messages_kind_check
  check (message_kind in ('text', 'image'));

alter table social.conversation_messages
  add constraint conversation_messages_text_length_check
  check (
    (message_kind = 'text' and char_length(trim(coalesce(message_text, ''))) between 1 and 2000)
    or (message_kind = 'image' and char_length(trim(coalesce(message_text, ''))) between 0 and 2000)
  );

create table if not exists social.conversation_message_media (
  id bigint generated by default as identity primary key,
  message_id bigint not null unique references social.conversation_messages(id) on delete cascade,
  conversation_id bigint not null references social.conversations(id) on delete cascade,
  uploaded_by_user_id text not null references core.users(id) on delete cascade,
  media_kind text not null default 'image',
  storage_path text not null,
  public_url text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint conversation_message_media_kind_check check (media_kind in ('image'))
);

create index if not exists idx_conversation_message_media_conversation
  on social.conversation_message_media (conversation_id, created_at desc);

create or replace trigger trg_user_blocks_touch_updated_at
before update on social.user_blocks
for each row execute function core.touch_updated_at();

create or replace trigger trg_conversation_message_media_touch_updated_at
before update on social.conversation_message_media
for each row execute function core.touch_updated_at();

alter table social.user_blocks enable row level security;
alter table social.conversation_message_media enable row level security;

drop policy if exists service_role_full on social.user_blocks;
create policy service_role_full
on social.user_blocks
for all
to service_role
using (true)
with check (true);

drop policy if exists service_role_full on social.conversation_message_media;
create policy service_role_full
on social.conversation_message_media
for all
to service_role
using (true)
with check (true);

drop policy if exists authenticated_user_blocks_select on social.user_blocks;
create policy authenticated_user_blocks_select
on social.user_blocks
for select
to authenticated
using (
  blocker_user_id = (select core.request_user_id())
  or blocked_user_id = (select core.request_user_id())
);

drop policy if exists authenticated_user_blocks_insert on social.user_blocks;
create policy authenticated_user_blocks_insert
on social.user_blocks
for insert
to authenticated
with check (
  blocker_user_id = (select core.request_user_id())
);

drop policy if exists authenticated_conversation_message_media_select on social.conversation_message_media;
create policy authenticated_conversation_message_media_select
on social.conversation_message_media
for select
to authenticated
using (
  exists (
    select 1
    from social.conversation_members cm
    where cm.conversation_id = social.conversation_message_media.conversation_id
      and cm.user_id = (select core.request_user_id())
  )
);

drop policy if exists authenticated_conversation_message_media_insert on social.conversation_message_media;
create policy authenticated_conversation_message_media_insert
on social.conversation_message_media
for insert
to authenticated
with check (
  uploaded_by_user_id = (select core.request_user_id())
  and exists (
    select 1
    from social.conversation_members cm
    where cm.conversation_id = social.conversation_message_media.conversation_id
      and cm.user_id = (select core.request_user_id())
  )
);

create or replace view compat.user_blocks as
select * from social.user_blocks;

create or replace view compat.conversation_message_media as
select * from social.conversation_message_media;

grant all on social.user_blocks to service_role;
grant all on social.conversation_message_media to service_role;
grant all on all sequences in schema social to service_role;

commit;
